# Generated by Django 3.1.4 on 2021-07-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('posts', '0003_post_commented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commented',
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='groupposts', to='groups.group'),
        ),
    ]
